# namespace-secret.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: wp-project

---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: wp-project
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: StrongPass@123
  MYSQL_DATABASE: wordpress
  MYSQL_USER: wpuser
  MYSQL_PASSWORD: WpPass@456
